version: 0.0.1.{build}-test

# Use default image unless needed
#os:
#- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.3.0
  matrix:
    - LUA_VER: 5.1.5
    # - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags disabled.
    #   NOCOMPAT: true
    # - LUA_VER: 5.3.2  # Lua 5.3.2 with compatibility flags disabled.
    #   NOCOMPAT: true
    # - LJ_VER: 2.0.4
    # - LJ_VER: 2.1

matrix:
  allow_failures:
    - configuration: 2010
      platform: x64
    - configuration: 2008
      platform: x64
    - configuration: MinGW
      platform: x64

# Abuse this section so we can have a matrix with different Compiler versions
# Is there a better way? Like injecting an array in the matrix?
configuration:
  - 2015

platform:
  - x86
  # - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

# Skip unsupported combinations (ie, VS2008 for x64 is not supported)
init:
  - if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )

install:
  # Make compiler command line tools available
  - call .appveyor\set_compiler_env.bat
  # Setup Lua development/build environment
  - call .appveyor\install.bat

before_build:
  - if "%LUA_VER%" EQU "5.1.5" (luarocks show bit32 || luarocks install bit32)
  - luarocks show luafilesystem || luarocks install luafilesystem

build_script:
  - luarocks make rockspecs/lua-path-scm-0.rockspec 

before_test:
  - luarocks show lunitx || luarocks install lunitx
  - luarocks show luacov || luarocks install luacov

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - lua run.lua
  - lua -lluacov test_lfs.lua

after_test:
# @todo
